### ISSUE TITLE
essential

### ISSUE THREAD

**Issue by Cosyspro** [dotnet/dotnet-maui-api-docs#100]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.storage.filebase?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/dotnet-maui-api-docs/blob/live/docs/xml/Microsoft.Maui.Storage/FileBase.xml

### Document Version Independent Id

7e921f6a-6380-d9e6-7771-43df78c30517

### Article author

@dotnet-bot

### Metadata

* ID: 7e921f6a-6380-d9e6-7771-43df78c30517 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by jfversluis** [comment]
Can you maybe elaborate on what you think the typo is? I don't see it :)

**Comment by jfversluis** [comment]
No response, so I assume this was by mistake.
