### ISSUE TITLE
Add more information about BrowserLaunchMode.SystemPreferred falling back to BrowserLaunchMode.External

### ISSUE THREAD

**Issue by mrlife** [dotnet/dotnet-maui-api-docs#101]
### Type of issue

Missing information

### Description

This page says:

> It's recommended to use the SystemPreferred as it is the default and gracefully falls back if needed.

Please add information about when/why this happens or how one might determine why it's happened when using the following in an app.

```C#
Uri uri = new Uri("https://www.microsoft.com");
await Browser.Default.OpenAsync(uri, BrowserLaunchMode.SystemPreferred);
```

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.applicationmodel.browserlaunchmode?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/dotnet-maui-api-docs/blob/live/docs/xml/Microsoft.Maui.ApplicationModel/BrowserLaunchMode.xml

### Document Version Independent Id

d8afd574-a0b6-86bc-eaeb-70696d79c5e4

### Article author

@dotnet-bot

### Metadata

* ID: d8afd574-a0b6-86bc-eaeb-70696d79c5e4 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by jfversluis** [comment]
I'm not really sure what you are asking? You mean how to detect that it didn't use the system preferred launch mode and how to handle that?

In either case, I think this is more something that should be described in the [conceptual docs](https://learn.microsoft.com/dotnet/maui/platform-integration/appmodel/open-browser), not the API docs.

**Comment by mrlife** [comment]
Hi @jfversluis, the purpose of this issue is to be able to find out _why_ it falls back. Currently, there is no information provided when it happens, at least that I can find.

I opened the issue on this page since it's the only place that mentions the fall-back behavior. If it needs to be opened in the [MAUI docs](https://github.com/dotnet/docs-maui/issues) instead, is it possible for this issue to be migrated there?

**Comment by jfversluis** [comment]
Ah OK! Looking at the code I actually can't really see what is meant by this statement. I don't see any evidence of .NET MAUI doing anything special in case it fails. If that even is the case, then that probably happens on the operating system level which is just echoed by our documentation here.

Sorry that I can't really clear it up for you. I will see if I can make the API docs here a bit more precise by either clarifying the why or how or remove this statement. Thanks for raising this!
