### ISSUE TITLE
IScreenshotResult: no matching element

### ISSUE THREAD

**Issue by davidbritch** [dotnet/dotnet-maui-api-docs#31]
The .NET 7 API docs build process has introduced the following into docs/xml/Microsoft.Maui.Media/IScreenshotResult.xml:

```
        <!-- No matching elements were found for the following include tag -->
         <include file="../../docs/Microsoft.Maui.Essentials/IScreenshotResult.xml" path="//Member[@MemberName='CopyToAsync']/Docs/*" />
```

This will most likely need removing, and the MAUI source correcting, before mdoc can update this file.

**Comment by jfversluis** [comment]
Should be fixed by: https://github.com/dotnet/maui/pull/11223

Although when merged it needs to be ported to the net7 branch
