### ISSUE TITLE
Doc cleanup: Links to Xamarin.Forms conceptual docs

### ISSUE THREAD

**Issue by davidbritch** [dotnet/dotnet-maui-api-docs#5]
Nine of the docs link to conceptual docs in the Xamarin.Forms docset. These links should be updated to point to .NET MAUI equivalents.

See https://github.com/dotnet/dotnet-maui-api-docs/search?q=xamarin-forms

**Comment by jfversluis** [comment]
Should be fixed in .NET 8 with: https://github.com/dotnet/maui/pull/17732
