### ISSUE TITLE
Doc cleanup: Links to developer.xamarin.com

### ISSUE THREAD

**Issue by davidbritch** [dotnet/dotnet-maui-api-docs#6]
A small number of docs attempt to link to developer.xamarin.com(!). These links should be updated to point to .NET MAUI equivalents.

See https://github.com/dotnet/dotnet-maui-api-docs/search?q=developer.xamarin.com

**Comment by jfversluis** [comment]
Should be fixed as of .NET 8 with: https://github.com/dotnet/maui/pull/17732
