### ISSUE TITLE
GraphicsView EndInteraction Event dont show which Touchpoint has been ended

### ISSUE THREAD

**Issue by mikiNoz** [dotnet/dotnet-maui-api-docs#66]
### Type of issue

Missing information

### Description

When i have e.g. two fingers on the graphics View and then release one finger, the EndInteraction will fire. so far so good. But in the TouchEventArgs parameter there is no information which finger has been released. So i cant do any logic, that depends on knowing the remaining touchpoint or the released touchpoint.  

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.graphicsview.microsoft-maui-igraphicsview-endinteraction?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/dotnet-maui-api-docs/blob/live/docs/xml/Microsoft.Maui.Controls/GraphicsView.xml

### Document Version Independent Id

df2bcee0-85d9-f33d-57ea-ea39502ee97a

### Article author

@dotnet-bot

### Metadata

* ID: df2bcee0-85d9-f33d-57ea-ea39502ee97a 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by mikiNoz** [comment]
someone is responsible for this?

**Comment by jfversluis** [comment]
Hey there! This repository is not for raising issues with the product but for issues with the API docs specifically. 

I hope you have it figured out by now. If not, please turn to https://github.com/dotnet/maui. If you have a how-to question you might want to start on the Discussions tab. If you think there is a bug in the .NET MAUI SDK, please open an issue. Thanks!
