### ISSUE TITLE
Microsoft.Maui.Handlers.WindowHandler

### ISSUE THREAD

**Issue by michaelrodriguezalvarez** [dotnet/dotnet-maui-api-docs#68]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.handlers.windowhandler?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/dotnet-maui-api-docs/blob/live/docs/xml/Microsoft.Maui.Handlers/WindowHandler.xml

### Document Version Independent Id

3b47507f-c031-7a8b-05b7-b7b25334de64

### Article author

@dotnet-bot

### Metadata

* ID: 3b47507f-c031-7a8b-05b7-b7b25334de64 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by jfversluis** [comment]
Please specify what typo and where, that will make it easier for us to locate and fix it, thanks!
