### ISSUE TITLE
API documentation for AuthenticateAsync is missing Exception information

### ISSUE THREAD

**Issue by peterfoot** [dotnet/dotnet-maui-api-docs#72]
### Type of issue

Missing information

### Description

[Enter feedback here]
When the user cancels out of the OAuth process this method throws a TaskCanceledException. This is not currently documented.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.authentication.webauthenticator.authenticateasync?view=net-maui-8.0&source=docs#microsoft-maui-authentication-webauthenticator-authenticateasync(microsoft-maui-authentication-webauthenticatoroptions)

### Content source URL

https://github.com/dotnet/dotnet-maui-api-docs/blob/live/docs/xml/Microsoft.Maui.Authentication/WebAuthenticator.xml

### Document Version Independent Id

4706e5e5-fdb0-11ea-4755-c16525a1b538

### Article author

@dotnet-bot

### Metadata

* ID: 4706e5e5-fdb0-11ea-4755-c16525a1b538 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by jfversluis** [comment]
I think this one is added in code now too @peterfoot ? 

Here: https://github.com/dotnet/maui/blob/8cd9239c283c1ba7398a8f6f3b063089582db3ff/src/Essentials/src/WebAuthenticator/WebAuthenticator.shared.cs#L21

Just needs publishing probably?

**Comment by peterfoot** [comment]
Thanks, happy to close this now. Why is it tagged Windows though? - the TaskCanceledException is used on iOS and Android too.

**Comment by jfversluis** [comment]
@peterfoot is that right? The only evidence could find in our code was this this is only happening on Windows? But happy to be proven wrong :)

**Comment by peterfoot** [comment]
We're using the Xamarin Essentials WebAuthenticator and if the user exits the flow (tapping X or Close) in either iOS or Android it throws this exception. We were initially surprised by it as it wasn't documented and I don't think TaskCanceledException is normally used for user interactions.

**Comment by jfversluis** [comment]
Interesting. A search for that exception also on Essentials only shows UWP code: https://github.com/search?q=repo%3Axamarin%2FEssentials%20TaskCanceledException&type=code

Maybe it doesn't originate from .NET MAUI/Xamarin.Essentials then? Anyway, I will open another PR to take off the Windows specific part. I'd rather have people be extra careful on all platforms with this and document too much than too little. Thanks for this!

**Comment by peterfoot** [comment]
Looking at the iOS code it is:-
else if (error.Domain == asWebAuthenticationSessionErrorDomain && error.Code == asWebAuthenticationSessionErrorCodeCanceledLogin)
					tcsResponse.TrySetCanceled();
				else if (error.Domain == sfAuthenticationErrorDomain && error.Code == sfAuthenticationErrorCanceledLogin)
					tcsResponse.TrySetCanceled();
				else
					tcsResponse.TrySetException(new NSErrorException(error));

Setting the task canceled here results in the TaskCanceledException as the consumer of the API. I haven't looked at the Android equivalent but I suspect it is using TrySetCanceled somewhere too.

**Comment by jfversluis** [comment]
Ah I see yeah thats why it didn't show up in my simple search. Anyway, merged a PR for changing this on MAUI API docs so that should be all good then now!
