### ISSUE TITLE
protected virtual void OnNavigatedTo (Microsoft.Maui.Controls.NavigatedToEventArgs args);

### ISSUE THREAD

**Issue by dawnwjj** [dotnet/dotnet-maui-api-docs#74]
### Type of issue

Typo

### Description

[在此处输入反馈]

### Page URL

https://learn.microsoft.com/zh-cn/dotnet/api/microsoft.maui.controls.page.onnavigatedto?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/dotnet-maui-api-docs/blob/live/docs/xml/Microsoft.Maui.Controls/Page.xml

### Document Version Independent Id

cf5e0ed8-c3af-d089-f21a-98c0407a9831

### Article author

@dotnet-bot

### Metadata

* ID: cf5e0ed8-c3af-d089-f21a-98c0407a9831 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by jfversluis** [comment]
Please specify what typo and where, that will make it easier for us to locate and fix it, thanks!

**Comment by jfversluis** [comment]
No response, so I assume this was by mistake. Thanks!
