### ISSUE TITLE
Border

### ISSUE THREAD

**Issue by chebetoa7** [dotnet/dotnet-maui-api-docs#77]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.border.-ctor?view=net-maui-8.0#microsoft-maui-controls-border-ctor

### Content source URL

https://github.com/dotnet/dotnet-maui-api-docs/blob/live/docs/xml/Microsoft.Maui.Controls/Border.xml

### Document Version Independent Id

45ed1e33-a270-a220-2e3c-ab5eb954691f

### Article author

@dotnet-bot

### Metadata

* ID: 45ed1e33-a270-a220-2e3c-ab5eb954691f 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by jfversluis** [comment]
Please specify what typo and where, that will make it easier for us to locate and fix it, thanks!

**Comment by jfversluis** [comment]
No response, so I assume this was by mistake
