### ISSUE TITLE
map

### ISSUE THREAD

**Issue by Ducvu1996** [dotnet/dotnet-maui-api-docs#78]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.maps.pin?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/dotnet-maui-api-docs/blob/live/docs/xml/Microsoft.Maui.Controls.Maps/Pin.xml

### Document Version Independent Id

b6af8ae9-c2ef-3730-385e-8fa602846230

### Article author

@dotnet-bot

### Metadata

* ID: b6af8ae9-c2ef-3730-385e-8fa602846230 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by jfversluis** [comment]
Please specify what typo and where, that will make it easier for us to locate and fix it, thanks!
