### ISSUE TITLE
missing info

### ISSUE THREAD

**Issue by ddepauli** [dotnet/dotnet-maui-api-docs#79]
### Type of issue

Missing information

### Description

nothing here

### Page URL

https://learn.microsoft.com/it-it/dotnet/api/microsoft.maui.controls.application.platformapptheme?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/dotnet-maui-api-docs/blob/live/docs/xml/Microsoft.Maui.Controls/Application.xml

### Document Version Independent Id

73d46d57-ff36-c3e9-34b5-3455f52e405e

### Article author

@dotnet-bot

### Metadata

* ID: 73d46d57-ff36-c3e9-34b5-3455f52e405e 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by jfversluis** [comment]
You're totally right! Unfortunately our coverage is not where we want it to be. Thank you for raising this. I will close this issue as its not specific to this 1 API but a broader undertaking. We are tracking that over on the .NET MAUI repo where we are slowly but surely making improvements.

Thank you for raising this!
