### ISSUE TITLE
miss

### ISSUE THREAD

**Issue by face1339** [dotnet/dotnet-maui-api-docs#91]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-gb/dotnet/api/microsoft.maui.controls.platformconfiguration.iosspecific.blureffectstyle?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/dotnet-maui-api-docs/blob/live/docs/xml/Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific/BlurEffectStyle.xml

### Document Version Independent Id

2f254b87-68be-d4c8-27d1-224b84086439

### Article author

@dotnet-bot

### Metadata

* ID: 2f254b87-68be-d4c8-27d1-224b84086439 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by jfversluis** [comment]
Could you please indicate what the typo is because I can't seem to find it

**Comment by jfversluis** [comment]
No response, so no clue what to do :) please let us know if this is still an issue. Thanks!
