### ISSUE TITLE
Mi fon

### ISSUE THREAD

**Issue by jjzamora451** [dotnet/dotnet-maui-api-docs#97]
### Type of issue

Typo

### Description

[Escriba sus comentarios aquí]

### Page URL

https://learn.microsoft.com/es-es/dotnet/api/microsoft.maui.accessibility.isemanticscreenreader?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/dotnet-maui-api-docs/blob/live/docs/xml/Microsoft.Maui.Accessibility/ISemanticScreenReader.xml

### Document Version Independent Id

f71d5aab-a541-3120-c1a0-83bd857458a3

### Article author

@dotnet-bot

### Metadata

* ID: f71d5aab-a541-3120-c1a0-83bd857458a3 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by jfversluis** [comment]
@jjzamora451 thanks! Could you maybe let me know what the typo is exactly? :)
